class ExistsError(Exception):
    pass


class DoesNotExistError(Exception):
    pass


class ClosedError(Exception):
    pass
